format = """
$os\
$username\
$hostname\
[](bg:#f5c2e7 fg:#89b4fa)\
$directory\
[](fg:#f5c2e7)\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$new_line
$character\
"""

add_newline = false

[username]
show_always = true
style_user = "bg:#89b4fa #494D64"
style_root = "bg:#89b4fa #494D64"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_only = false
style = "bg:#89b4fa #494D64"
format = "[@$ssh_symbol$hostname ]($style)"

[character]
success_symbol = "[◯](bold #a6e3a1)"
error_symbol = "[✗](bold #f38ba8)"

[os]
style = "bg:#89b4fa"
disabled = false

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[directory]
style = "bg:#f5c2e7 #494D64"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "..\ue5fe../"

#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = " "
#"Pictures" = " "

[git_branch]
symbol = ""
style = "#b4befe"
format = '[ \($symbol $branch ]($style)'

[git_status]
style = "#b4befe"
format = '[\[$all_status$ahead_behind\]\)]($style)'

[c]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[elixir]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[elm]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[golang]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[gradle]
style = "#fab387"
format = '[ \($symbol ($version)\) ]($style)'

[haskell]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[java]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[julia]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[nodejs]
style = "#fab387"
symbol = ""
format = '[ \($symbol ($version)\) ]($style)'

[nim]
style = "#fab387"
symbol = "󰆥 "
format = '[ \($symbol ($version)\) ]($style)'

[rust]
style = "#fab387"
symbol = ""
format = '[ \($symbol ($version)\) ]($style)'

[scala]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

[zig]
style = "#fab387"
symbol = " "
format = '[ \($symbol ($version)\) ]($style)'

