# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

# powerline
eval "$(oh-my-posh init bash --config ~/.poshthemes/catppuccin.omp.json)"

# Alias definitions
alias hypr='nvim ~/.config/hypr/hyprland.conf'
alias wisdom='fortune | cowsay'
alias present='impressive -q -t None'
alias clock='tty-clock -c -C 3'

export EDITOR=nvim
